<?php

namespace App\Http\Requests;

use App\Http\Requests\Request;

class CalendarRequest extends Request
{
    function wantsJson()
    {
        return true; // TODO: Change the autogenerated stub
    }

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'res_turn_id' => 'required|exists:res_turn,id,ms_microsite_id,'.$this->route('microsite_id'),
            'date' => 'required|date'
        ];
    }
}
